/**
 * Valyrian Edge - Report Generator
 * Generates security assessment reports in multiple formats
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import type {
    SecurityReport,
    Finding,
} from '../types/index.js';
import { createLogger } from '../utils/logger.js';

const logger = createLogger('report-generator');

// =============================================================================
// TYPES
// =============================================================================

export type OutputFormat = 'markdown' | 'html' | 'json' | 'sarif';

export interface GeneratorOptions {
    format: OutputFormat;
    outputPath: string;
    includePOC?: boolean;
    redactSensitive?: boolean;
    branding?: {
        companyName?: string;
        logoUrl?: string;
    };
}

// =============================================================================
// REPORT GENERATOR
// =============================================================================

export class ReportGenerator {
    private report: SecurityReport;
    private options: GeneratorOptions;

    constructor(report: SecurityReport, options: GeneratorOptions) {
        this.report = report;
        this.options = options;
    }

    async generate(): Promise<string> {
        let content: string;

        switch (this.options.format) {
            case 'markdown':
                content = this.generateMarkdown();
                break;
            case 'html':
                content = this.generateHTML();
                break;
            case 'json':
                content = this.generateJSON();
                break;
            case 'sarif':
                content = this.generateSARIF();
                break;
            default:
                throw new Error(`Unsupported format: ${this.options.format}`);
        }

        // Ensure output directory exists
        await mkdir(dirname(this.options.outputPath), { recursive: true });

        // Write the report
        await writeFile(this.options.outputPath, content, 'utf-8');

        logger.info({
            format: this.options.format,
            path: this.options.outputPath,
        }, 'Report generated');

        return content;
    }

    // ===========================================================================
    // MARKDOWN FORMAT
    // ===========================================================================

    private generateMarkdown(): string {
        const { report, options } = this;
        const lines: string[] = [];

        // Header
        lines.push('# Security Assessment Report');
        lines.push('');
        if (options.branding?.companyName) {
            lines.push(`*Generated by ${options.branding.companyName}*`);
        }
        lines.push(`*Report ID: ${report.metadata.reportId}*`);
        lines.push(`*Generated: ${report.metadata.generatedAt.toISOString()}*`);
        lines.push('');

        // Executive Summary
        lines.push('## Executive Summary');
        lines.push('');
        lines.push(`**Target:** ${report.scope.targetDescription}`);
        lines.push(`**Overall Risk:** ${report.executiveSummary.overallRisk.toUpperCase()}`);
        lines.push('');
        lines.push('### Findings Summary');
        lines.push('');
        lines.push('| Severity | Count |');
        lines.push('|----------|-------|');
        lines.push(`| 🔴 Critical | ${report.executiveSummary.criticalCount} |`);
        lines.push(`| 🟠 High | ${report.executiveSummary.highCount} |`);
        lines.push(`| 🟡 Medium | ${report.executiveSummary.mediumCount} |`);
        lines.push(`| 🔵 Low | ${report.executiveSummary.lowCount} |`);
        lines.push('');

        // Key Risks
        if (report.executiveSummary.keyRisks.length > 0) {
            lines.push('### Key Risks');
            lines.push('');
            for (const risk of report.executiveSummary.keyRisks) {
                lines.push(`- ${risk}`);
            }
            lines.push('');
        }

        // Immediate Actions
        if (report.executiveSummary.immediateActions.length > 0) {
            lines.push('### Immediate Actions Required');
            lines.push('');
            for (const action of report.executiveSummary.immediateActions) {
                lines.push(`- ${action}`);
            }
            lines.push('');
        }

        // Scope
        lines.push('## Scope');
        lines.push('');
        lines.push(`- **Target URL:** ${report.scope.targetUrl}`);
        lines.push(`- **Architecture:** ${report.scope.architecture}`);
        lines.push(`- **LLM Provider:** ${report.scope.llmProvider ?? 'Unknown'}`);
        lines.push('');

        // Detailed Findings
        lines.push('## Detailed Findings');
        lines.push('');

        for (const finding of report.findings) {
            lines.push(this.formatFindingMarkdown(finding));
        }

        // PoC Scripts (if enabled)
        if (options.includePOC && report.appendices.pocScripts.length > 0) {
            lines.push('## Proof of Concept Scripts');
            lines.push('');
            for (const poc of report.appendices.pocScripts) {
                lines.push(`### ${poc.language.toUpperCase()} - ${poc.id}`);
                lines.push('');
                lines.push('```' + poc.language);
                lines.push(poc.script);
                lines.push('```');
                lines.push('');
            }
        }

        // Technical Details
        lines.push('## Technical Details');
        lines.push('');
        lines.push('### Chatbot Profile');
        lines.push('');
        lines.push('```json');
        lines.push(JSON.stringify(report.chatbotProfile, null, 2));
        lines.push('```');
        lines.push('');

        // Metadata
        lines.push('## Metadata');
        lines.push('');
        lines.push(`- **Tool Version:** ${report.metadata.version}`);
        lines.push(`- **Duration:** ${report.metadata.durationMinutes} minutes`);
        lines.push(`- **LLM Cost:** $${report.metadata.llmCostUsd.toFixed(4)}`);
        lines.push('');

        return lines.join('\n');
    }

    private formatFindingMarkdown(finding: Finding): string {
        const lines: string[] = [];

        lines.push(`### ${this.getSeverityEmoji(finding.severity)} ${finding.title}`);
        lines.push('');
        lines.push(`**Severity:** ${finding.severity.toUpperCase()}`);
        lines.push(`**CVSS Score:** ${finding.cvssScore.toFixed(1)}`);
        lines.push(`**OWASP Category:** ${finding.owaspCategory}`);
        lines.push(`**Status:** ${finding.status}`);
        lines.push('');
        lines.push(finding.description);
        lines.push('');

        if (finding.impact.length > 0) {
            lines.push('#### Impact');
            lines.push('');
            for (const impact of finding.impact) {
                lines.push(`- ${impact}`);
            }
            lines.push('');
        }

        if (finding.remediation.length > 0) {
            lines.push('#### Remediation');
            lines.push('');
            for (const rem of finding.remediation) {
                lines.push(`- **${rem.priority}:** ${rem.action}`);
            }
            lines.push('');
        }

        return lines.join('\n');
    }

    // ===========================================================================
    // HTML FORMAT
    // ===========================================================================

    private generateHTML(): string {
        const markdown = this.generateMarkdown();

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Assessment Report - ${this.report.scope.targetDescription}</title>
    <style>
        :root {
            --bg: #0a0a0f;
            --surface: #1a1a2e;
            --text: #e0e0e0;
            --accent: #7f5af0;
            --critical: #ff4757;
            --high: #ff7f50;
            --medium: #ffd700;
            --low: #4ecdc4;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 2rem;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        h1, h2, h3 { color: white; margin-top: 2rem; margin-bottom: 1rem; }
        h1 { color: var(--accent); font-size: 2.5rem; }
        h2 { border-bottom: 2px solid var(--surface); padding-bottom: 0.5rem; }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
        th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid var(--surface); }
        th { background: var(--surface); }
        code { background: var(--surface); padding: 0.2rem 0.5rem; border-radius: 4px; }
        pre { background: var(--surface); padding: 1rem; border-radius: 8px; overflow-x: auto; margin: 1rem 0; }
        ul { margin-left: 2rem; margin-bottom: 1rem; }
        a { color: var(--accent); }
    </style>
</head>
<body>
    <div class="container">
        <pre id="content" style="background: transparent; white-space: pre-wrap;">${markdown}</pre>
    </div>
</body>
</html>`;
    }

    // ===========================================================================
    // JSON FORMAT
    // ===========================================================================

    private generateJSON(): string {
        const output = { ...this.report };

        if (this.options.redactSensitive) {
            // Redact sensitive data from PoC scripts
            for (const poc of output.appendices.pocScripts) {
                poc.script = '[REDACTED]';
            }
        }

        return JSON.stringify(output, (_key, value) => {
            if (value instanceof Date) {
                return value.toISOString();
            }
            return value;
        }, 2);
    }

    // ===========================================================================
    // SARIF FORMAT (for CI/CD integration)
    // ===========================================================================

    private generateSARIF(): string {
        const sarif = {
            $schema: 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json',
            version: '2.1.0',
            runs: [{
                tool: {
                    driver: {
                        name: 'Valyrian Edge',
                        version: this.report.metadata.version,
                        informationUri: 'https://valyrian-edge.io',
                        rules: this.report.findings.map(f => ({
                            id: f.owaspCategory,
                            name: f.title,
                            shortDescription: { text: f.description.slice(0, 100) },
                            fullDescription: { text: f.description },
                            defaultConfiguration: {
                                level: this.mapSeverityToSARIF(f.severity),
                            },
                            helpUri: `https://owasp.org/www-project-machine-learning-security-top-10/${f.owaspCategory}`,
                        })),
                    },
                },
                results: this.report.findings.map(f => ({
                    ruleId: f.owaspCategory,
                    level: this.mapSeverityToSARIF(f.severity),
                    message: {
                        text: f.description,
                    },
                    locations: [{
                        physicalLocation: {
                            artifactLocation: {
                                uri: this.report.scope.targetUrl,
                            },
                        },
                    }],
                    partialFingerprints: {
                        primaryLocationLineHash: f.id,
                    },
                })),
            }],
        };

        return JSON.stringify(sarif, null, 2);
    }

    // ===========================================================================
    // HELPERS
    // ===========================================================================

    private getSeverityEmoji(severity: string): string {
        switch (severity) {
            case 'critical': return '🔴';
            case 'high': return '🟠';
            case 'medium': return '🟡';
            case 'low': return '🔵';
            default: return 'ℹ️';
        }
    }

    private mapSeverityToSARIF(severity: string): string {
        switch (severity) {
            case 'critical':
            case 'high':
                return 'error';
            case 'medium':
                return 'warning';
            default:
                return 'note';
        }
    }
}

// =============================================================================
// FACTORY
// =============================================================================

export function createReportGenerator(
    report: SecurityReport,
    options: GeneratorOptions
): ReportGenerator {
    return new ReportGenerator(report, options);
}

export default ReportGenerator;
